spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=h123456aA@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


app.jwt.secret-key=9dnsON1Ntzv3pJvOMsLrlufdlMFEiWZro8U/vnRkfryT0vHGYOhDtdvctyt6lo/p
app.jwt.access-token-expiration=30
app.jwt.refresh-token-expiration=604800