spring:
  application:
    name: ecommerce
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: h123456aA@
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
      timeout: 60000
  
  jpa:
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret-key: 9dnsON1Ntzv3pJvOMsLrlufdlMFEiWZro8U/vnRkfryT0vHGYOhDtdvctyt6lo/p
    access-token-expiration: 86400
    refresh-token-expiration: 604800

gcs:
  bucket-name:  ecommerce-app-storage
  credentials: C:\WorkSpace\Spring\GGCL-KEY\my-ecommerce-app-479317-f5f333f7c8b5.json
  base-url: https://storage.googleapis.com
  project-id: my-ecommerce-app-479317

